# Generated by Django 5.0.7 on 2026-07-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="crm_activit_action_ced24b_idx",
            old_name="crm_activit_action_27094d_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="crm_activit_created_5dbfb2_idx",
            old_name="crm_activit_created_5753a0_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="crm_activit_lead_id_d5dc8c_idx",
            old_name="crm_activit_lead_id_d0b06b_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="crm_activit_actor_i_0c28a1_idx",
            old_name="crm_activit_actor_i_a8752a_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_lead_status_2c1bc7_idx",
            old_name="crm_lead_status_1c6284_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_lead_priorit_fb8cee_idx",
            old_name="crm_lead_priorit_757108_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_lead_source_0cf4cf_idx",
            old_name="crm_lead_source_03ef26_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_lead_assigne_36bf8f_idx",
            old_name="crm_lead_assigne_c21f86_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_lead_created_d9bbc3_idx",
            old_name="crm_lead_created_9a0dcf_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_lead_updated_46dd1a_idx",
            old_name="crm_lead_updated_edf1a8_idx",
        ),
        migrations.RenameIndex(
            model_name="leadnote",
            new_name="crm_leadnot_lead_id_1321d1_idx",
            old_name="crm_leadnot_lead_id_30f7d5_idx",
        ),
        migrations.RenameIndex(
            model_name="leadnote",
            new_name="crm_leadnot_author__f99249_idx",
            old_name="crm_leadnot_author__e6cc7c_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="crm_user_role_943b00_idx",
            old_name="crm_user_role_940f8d_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="crm_user_is_acti_40cb97_idx",
            old_name="crm_user_is_acti_1bb70c_idx",
        ),
    ]
